// Runs actual native Mixxx/WebRTC/Opus peers. Deliberately no signaling-server
// imports or process: the only exchange is the text passed by this test.
import assert from 'node:assert/strict';
import test from 'node:test';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
const binary=process.env.PLUMDECK_TEST_HOST||path.resolve(import.meta.dirname,'../../build-upstream/plumdeck-mixxx-engine-host');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(read,predicate,label,timeout=40000){const end=Date.now()+timeout;let last;while(Date.now()<end){last=await read();if(predicate(last))return last;await pause(60);}throw Error(`${label}: timed out; phase=${last?.handoffState}, connection=${last?.connection?.state}`);}
function native(directory){
 const child=spawn(binary,[],{env:{...process.env,PLUMDECK_JUNCTION_EPHEMERAL_NETWORK:'1',PLUMDECK_MIXXX_OUTPUT_DEVICE:process.env.PLUMDECK_MIXXX_OUTPUT_DEVICE||'BlackHole 2ch',PLUMDECK_MIXXX_RECORDING_DIR:directory}});
 let hello,id=0,stderr='';const pending=new Map();child.stderr.on('data',b=>{stderr=(stderr+b).slice(-3000);});
 const reject=reason=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(reason);}pending.clear();};child.on('error',reject);child.on('exit',code=>reject(Error(`Native exited: ${code}`)));
 createInterface({input:child.stdout}).on('line',line=>{let reply;try{reply=JSON.parse(line);}catch{return;}const p=pending.get(reply.id);if(p){clearTimeout(p.timer);pending.delete(reply.id);p.resolve(reply);}});
 const raw=(op,params={})=>{if(child.exitCode!==null||child.signalCode!==null)return Promise.reject(Error(`Native already exited: ${child.exitCode}/${child.signalCode}`));const current=++id;const promise=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(current);reject(Error(`Native ${op} timed out`));},15000);pending.set(current,{resolve,reject,timer});});child.stdin.write(JSON.stringify({id:current,op,params,...(hello?{engineId:hello.engineId,sessionId:hello.sessionId}:{})})+'\n');return promise;};
 const command=async(op,params={})=>{const r=await raw(op,params);assert(r.kind!=='error'&&r.ok!==false,`${op}: ${r.error?.message||'native error'}`);return r.data??r;};
 return {command,raw,snapshot:()=>command('junction.snapshot'),suspend:()=>child.kill('SIGSTOP'),resume:()=>child.kill('SIGCONT'),async start(){hello=await command('session.hello');await until(()=>command('state.snapshot'),s=>s.audio.applied,'audio configuration');await command('junction.network.configure',{stunUrls:[],turn:{},save:false});},async close(){child.kill('SIGCONT');child.stdin.end();if(child.exitCode===null&&child.signalCode===null)await Promise.race([new Promise(r=>child.once('exit',r)),pause(4000)]);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(r=>child.once('exit',r));}assert.equal(child.exitCode,0,`clean native exit (${child.signalCode}); ${stderr}`);}};
}
function tone(){const rate=48000,n=rate*240,b=Buffer.alloc(44+n*4);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(2,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*4,28);b.writeUInt16LE(4,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*4,40);for(let i=0;i<n;i++){const x=Math.round(7500*Math.sin(i*2*Math.PI*440/rate)+1700*Math.sin(i*2*Math.PI*733.37/rate));b.writeInt16LE(x,44+i*4);b.writeInt16LE(x,46+i*4);}return b;}
function recordedPcm(bytes){assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.equal(bytes.readUInt32LE(4)+8,bytes.length);let pcm,bits,channels;for(let p=12;p+8<=bytes.length;){const n=bytes.readUInt32LE(p+4),tag=bytes.toString('ascii',p,p+4);if(tag==='fmt '){channels=bytes.readUInt16LE(p+10);bits=bytes.readUInt16LE(p+22);}if(tag==='data')pcm=bytes.subarray(p+8,p+8+n);p+=8+n+(n%2);}assert.equal(bits,24);assert.equal(channels,2);assert(pcm.length>48000);let energy=0;for(let p=0;p+3<=pcm.length;p+=3){const x=pcm.readIntLE(p,3)/8388608;energy+=x*x;}assert(Math.sqrt(energy/(pcm.length/3))>.005,'real Program audio is non-silent');// Exclude only the recorder's opening half-second; admission/handoff/re-exchange happen later.
let silence=0,longest=0,longestAt=0;for(let p=48000*6/2;p+6<=pcm.length;p+=6){silence=Math.abs(pcm.readIntLE(p,3)/8388608)<.0001?silence+1:0;if(silence>longest){longest=silence;longestAt=p/6-silence;}}assert(longest<=240,`handoff/re-exchange Program silence ${longest/48}ms at ${longestAt/48000}s exceeds 5ms`);}
const participant=(s,id)=>s.participants.find(p=>p.peerId===id);
async function readyInvite(host,id){return until(host.snapshot,s=>participant(s,id)?.exchange?.inviteText?.length>0,'both offers complete');}
async function newInvite(host,peerId){const before=await host.snapshot();await host.command('junction.invite.create',peerId?{peerId}:{});const created=await host.snapshot();const peer=peerId?participant(created,peerId):created.participants.find(p=>p.peerId!==created.localPeerId&&!before.participants.some(old=>old.peerId===p.peerId));assert(peer,'individual invitation card exists');if(peer.exchange.state==='collecting')assert(!peer.exchange.inviteText,'unfinished gathering is not exportable');const ready=await readyInvite(host,peer.peerId);return {peerId:peer.peerId,text:participant(ready,peer.peerId).exchange.inviteText};}
async function response(guest,text,name){await guest.command('junction.exchange.inspect',{text});await guest.command('junction.join',{displayName:name,text});const s=await until(guest.snapshot,s=>s.exchange?.responseText?.length>0,'both answers complete');return s.exchange.responseText;}
const denied=r=>r.kind==='error'||r.ok===false;
test('manual multi-DJ admission, cancellation, handoff and same-peer re-exchange without a signaling server',{timeout:300000},async()=>{
 const relay=Boolean(process.env.JUNCTION_TURN_ADDRESS);
 const directory=await mkdtemp('/tmp/plumdeck-manual-runtime-');const host=native(directory),first=native(directory),second=native(directory);const peers=[host,first,second];
 try{
  for(const peer of peers)await peer.start();console.info('native engines ready');
  if(relay){
    const secret=(await readFile(process.env.JUNCTION_TURN_SECRET_FILE,'utf8')).trim();
    const summary=await host.command('junction.network.configure',{stunUrls:[],turn:{mode:'rest',urls:['turn:'+process.env.JUNCTION_TURN_ADDRESS],secret},save:false});
    assert(!JSON.stringify(summary).includes(secret),'admin secret never returned');
    const probe=await host.command('junction.network.test');assert.equal(probe.state,'checking');
    const tested=await until(()=>host.command('junction.network.test',{poll:true}),s=>s.state!=='checking','actual TURN allocation',35000);assert.equal(tested.state,'success',tested.detail);
  }
  const source=path.join(directory,'tone.wav');await writeFile(source,tone());await host.command('deck.load',{deck:'A',track:{trackId:'manual-tone',path:source,title:'Manual session tone'}});await until(()=>host.command('state.snapshot'),s=>['ready','paused'].includes(s.decks.A.status),'tone decode');await host.command('deck.play',{deck:'A'});
  const devices=await host.command('audio.devices.list');const output=devices.devices.find(d=>d.name.includes('BlackHole')&&d.outputChannels>=2);assert(output,'loopback device required, not skipped');
  await host.command('junction.create',{displayName:'ホスト DJ',sessionName:'手動でつなぐセッション',programDevice:output.id.replace(/^coreaudio:/,''),adoptCurrent:true,exchangeMode:'manual'});
  const created=await until(host.snapshot,s=>s.active&&s.program.state==='running','server-free host and Program');assert.equal(created.exchange.mode,'manual');assert.equal(created.performerPeerId,created.localPeerId);const epoch=created.epoch;
  console.info('manual host ready');const one=await newInvite(host),two=await newInvite(host);console.info('two invitations collected');assert.notEqual(one.peerId,two.peerId);
  if(relay){const packet=JSON.parse(Buffer.from(one.text.split('.')[1],'base64url'));assert(packet.iceServers.some(s=>s.credential&&s.expiresAt>Date.now()));assert(!packet.iceServers.some(s=>'secret' in s));}
  const inspected=await first.command('junction.exchange.inspect',{text:one.text});assert.equal(inspected.sessionName,'手動でつなぐセッション');
  assert(denied(await first.raw('junction.exchange.inspect',{text:one.text.slice(0,Math.floor(one.text.length/2))})),'truncated invitation rejected');
  const answerOne=await response(first,one.text,'参加 DJ 1'),answerTwo=await response(second,two.text,'参加 DJ 2');
  await host.command('junction.exchange.import',{text:answerTwo});await host.command('junction.exchange.import',{text:answerOne});
  let s=await host.snapshot();for(const id of [one.peerId,two.peerId]){assert.equal(participant(s,id).exchange.state,'approval_pending');assert.equal(participant(s,id).approved,false);}assert.equal(s.performerPeerId,created.localPeerId);assert.equal(s.epoch,epoch);
  await host.raw('junction.exchange.import',{text:answerTwo});s=await host.snapshot();assert.equal(participant(s,two.peerId).exchange.state,'approval_pending','duplicate import cannot connect or reset card');
  await host.command('junction.invite.cancel',{peerId:one.peerId});assert(denied(await host.raw('junction.exchange.import',{text:answerOne})),'cancelled invitation refuses stale response');
  s=await host.snapshot();assert.equal(participant(s,two.peerId).exchange.state,'approval_pending','other invitation preserved');
  const notice=participant(s,one.peerId).exchange.noticeText;assert(notice,'signed offline cancellation available');if(notice){await first.command('junction.exchange.import',{text:notice});assert(['cancelled','rejected','expired'].includes((await first.snapshot()).exchange.state));}
  await host.command('junction.peer.approve',{peerId:two.peerId,accept:true});await until(second.snapshot,s=>s.connection.state==='connected','approved P2P connection');
  s=await host.snapshot();assert.equal(participant(s,two.peerId).exchange.route,relay?'relay':'direct');assert.equal(s.performerPeerId,created.localPeerId);assert.equal(s.epoch,epoch);assert.equal((await second.snapshot()).readiness.ready,false,'connection is not musical readiness');
  const query=await second.raw('engine.clock.probe');assert(!denied(query),'waiting DJ can inspect timing');assert(denied(await second.raw('deck.pause',{deck:'A'})),'waiting DJ cannot mutate shared deck');
  const retry=await newInvite(host,one.peerId);assert.notEqual(retry.text,one.text);await first.command('junction.exchange.import',{text:retry.text});const newAnswer=await until(first.snapshot,s=>s.exchange?.responseText?.length>0,'replacement response');await host.command('junction.exchange.import',{text:newAnswer.exchange.responseText});await host.command('junction.peer.approve',{peerId:one.peerId,accept:true});await until(first.snapshot,s=>s.connection.state==='connected','second independent guest');
  await until(host.snapshot,s=>participant(s,one.peerId).exchange.state==='connected','both first guest channels connected');
  const recordedAt=Date.now();const recording=path.join(directory,'program.wav');await host.command('junction.program.record.start',{path:recording});first.suspend();await until(host.snapshot,s=>participant(s,one.peerId).exchange.state==='interrupted','detect transient interruption',7000);first.resume();await until(host.snapshot,s=>participant(s,one.peerId).exchange.state==='connected','transient communication returns');assert.equal((await host.snapshot()).performerPeerId,created.localPeerId,'transient interruption never transfers ownership');
  await host.command('junction.handoff.request',{targetPeerId:two.peerId});await until(second.snapshot,s=>s.readiness.ready,'real graph/music readiness',80000);await second.command('junction.handoff.accept');const owner=await until(second.snapshot,s=>s.performerPeerId===s.localPeerId&&BigInt(s.epoch)>BigInt(epoch),'actual manual-session handoff',80000);await until(host.snapshot,s=>s.handoffState==='playing'&&s.performerPeerId===two.peerId,'Program cutover');
  console.info('re-exchange begins seconds', (Date.now()-recordedAt)/1000);const reconnect=await newInvite(host,two.peerId);await second.command('junction.exchange.import',{text:reconnect.text});const fresh=await until(second.snapshot,s=>s.exchange?.responseText&&s.exchange.responseText!==answerTwo,'live replacement response');await host.command('junction.exchange.import',{text:fresh.exchange.responseText});await host.command('junction.peer.approve',{peerId:two.peerId,accept:true});await until(host.snapshot,s=>participant(s,two.peerId)?.exchange.state==='connected','replacement P2P connection');
  s=await host.snapshot();assert.equal(s.performerPeerId,two.peerId);assert.equal(s.epoch,owner.epoch,'reconnection never changes epoch');assert.equal(participant(s,one.peerId).exchange.state,'connected','other DJ unaffected by re-exchange');assert(denied(await host.raw('junction.exchange.import',{text:answerTwo})),'old response cannot replace new connection');
  await pause(700);await host.command('junction.program.record.stop');console.info('recording ends seconds',(Date.now()-recordedAt)/1000);recordedPcm(await readFile(recording));second.suspend();await pause(650);second.resume();await until(host.snapshot,s=>s.handoffState==='playing'&&s.performerPeerId===two.peerId&&Number(s.program.rms)>.001,'current performer resumes after brief outage');assert.equal((await host.snapshot()).epoch,owner.epoch);
  first.suspend();await until(host.snapshot,s=>participant(s,one.peerId).exchange.state==='needs_exchange','prolonged outage requires fresh exchange',23000);const kept=await host.snapshot();assert.equal(kept.performerPeerId,two.peerId);assert.equal(kept.epoch,owner.epoch);assert.equal(participant(kept,two.peerId).exchange.state,'connected');
  const renewed=await newInvite(host,one.peerId);first.resume();await first.command('junction.exchange.import',{text:renewed.text});const renewedReply=await until(first.snapshot,s=>s.exchange?.responseText,'new reply after prolonged outage');await host.command('junction.exchange.import',{text:renewedReply.exchange.responseText});await host.command('junction.peer.approve',{peerId:one.peerId,accept:true});await until(host.snapshot,s=>participant(s,one.peerId).exchange.state==='connected','same peer after prolonged outage');
  await host.command('junction.end');await until(host.snapshot,s=>!s.active,'graceful host end');for(const guest of [first,second])await until(guest.snapshot,s=>!s.active,'guest end');
 }finally{const closed=await Promise.allSettled(peers.map(peer=>peer.close()));await rm(directory,{recursive:true,force:true});for(const result of closed)if(result.status==='rejected')throw result.reason;}
});
