# Same pinned class layout and algorithms; friend access only for the typed,
# stopped-graph checkpoint adapter. The upstream checkout remains untouched.
set(JUNCTION_MIX_HEADERS "${CMAKE_BINARY_DIR}/junction-headers")
foreach(header engine/enginebuffer.h engine/readaheadmanager.h engine/bufferscalers/enginebufferscale.h engine/bufferscalers/enginebufferscalest.h engine/bufferscalers/enginebufferscalerubberband.h)
  file(READ "${CMAKE_SOURCE_DIR}/src/${header}" contents)
  get_filename_component(name "${header}" NAME_WE)
  if(name STREQUAL "enginebuffer")
    set(class EngineBuffer)
  elseif(name STREQUAL "readaheadmanager")
    set(class ReadAheadManager)
  elseif(name STREQUAL "enginebufferscale")
    set(class EngineBufferScale)
  elseif(name STREQUAL "enginebufferscalest")
    set(class EngineBufferScaleST)
  else()
    set(class EngineBufferScaleRubberBand)
  endif()
  string(REGEX REPLACE "(class ${class}[^;{]*\\{)" "\\1\n    friend class ::junction::keylock::Access;" patched "${contents}")
  if(patched STREQUAL contents)
    message(FATAL_ERROR "Pinned keylock class hook differs: ${header}")
  endif()
  set(patched "namespace junction { namespace keylock { class Access; } }\n${patched}")
  set(output "${JUNCTION_MIX_HEADERS}/${header}")
  if(EXISTS "${output}")
    file(READ "${output}" previous)
  else()
    set(previous "")
  endif()
  if(NOT previous STREQUAL patched)
    file(WRITE "${output}" "${patched}")
  endif()
endforeach()
target_include_directories(mixxx-lib BEFORE PRIVATE "${JUNCTION_MIX_HEADERS}")
target_include_directories(plumdeck-mixxx-engine-host BEFORE PRIVATE "${JUNCTION_MIX_HEADERS}")
target_sources(plumdeck-mixxx-engine-host PRIVATE "${PLUMDECK_ROOT}/src/junction/keylock_engine.cpp")
find_package(Python3 COMPONENTS Interpreter REQUIRED)
add_custom_target(plumdeck-keylock-moc
  COMMAND "${Python3_EXECUTABLE}" "${PLUMDECK_ROOT}/scripts/fix-keylock-moc.py" "${CMAKE_BINARY_DIR}"
  DEPENDS mixxx-lib_autogen VERBATIM)
get_target_property(junction_original_deps mixxx-lib MANUALLY_ADDED_DEPENDENCIES)
if(junction_original_deps)
  set_property(TARGET mixxx-lib APPEND PROPERTY AUTOGEN_TARGET_DEPENDS ${junction_original_deps})
endif()
set_property(TARGET mixxx-lib PROPERTY AUTOGEN_ORIGIN_DEPENDS OFF)
add_dependencies(mixxx-lib plumdeck-keylock-moc)

execute_process(COMMAND "${Python3_EXECUTABLE}" "${PLUMDECK_ROOT}/scripts/prepare-fx-checkpoint.py" "${CMAKE_SOURCE_DIR}/src" "${JUNCTION_MIX_HEADERS}" COMMAND_ERROR_IS_FATAL ANY)
target_sources(plumdeck-mixxx-engine-host PRIVATE "${PLUMDECK_ROOT}/src/junction/fx_engine.cpp")

add_executable(junction-fx-tests EXCLUDE_FROM_ALL "${PLUMDECK_ROOT}/src/junction/fx_engine.cpp")
get_target_property(junction_native_includes plumdeck-mixxx-engine-host INCLUDE_DIRECTORIES)
get_target_property(junction_native_libraries plumdeck-mixxx-engine-host LINK_LIBRARIES)
target_include_directories(junction-fx-tests PRIVATE ${junction_native_includes})
target_link_libraries(junction-fx-tests PRIVATE ${junction_native_libraries})
target_compile_definitions(junction-fx-tests PRIVATE PLUMDECK_JUNCTION_FX_TEST_MAIN=1)
set_target_properties(junction-fx-tests PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON)
set_source_files_properties("${PLUMDECK_ROOT}/src/junction/fx_engine.cpp" PROPERTIES INCLUDE_DIRECTORIES "${CMAKE_SOURCE_DIR}/lib/reverb")
