set(JUNCTION_RB_ROOT "${CMAKE_CURRENT_LIST_DIR}/../build-deps/rubberband")
if(NOT EXISTS "${JUNCTION_RB_ROOT}/build/librubberband.a")
  message(FATAL_ERROR "Build the pinned RubberBand checkpoint dependency with scripts/build-rubberband-checkpoint.sh")
endif()
add_library(djaly-rubberband-state INTERFACE)
target_include_directories(djaly-rubberband-state INTERFACE "${JUNCTION_RB_ROOT}/source")
target_link_libraries(djaly-rubberband-state INTERFACE "${JUNCTION_RB_ROOT}/build/librubberband.a" "${JUNCTION_samplerate_LIBRARY}" "-framework Accelerate")
if(TARGET rubberband::rubberband)
 set_target_properties(rubberband::rubberband PROPERTIES IMPORTED_LOCATION "${JUNCTION_RB_ROOT}/build/librubberband.a" INTERFACE_INCLUDE_DIRECTORIES "${JUNCTION_RB_ROOT}/source")
endif()
