set(JUNCTION_RB_ROOT "${CMAKE_CURRENT_LIST_DIR}/../build-deps/rubberband")
if(WIN32)
  set(JUNCTION_RB_LIBRARY "${JUNCTION_RB_ROOT}/build/rubberband.lib")
else()
  set(JUNCTION_RB_LIBRARY "${JUNCTION_RB_ROOT}/build/librubberband.a")
endif()
if(NOT EXISTS "${JUNCTION_RB_LIBRARY}")
  message(FATAL_ERROR "Build the pinned RubberBand checkpoint dependency with scripts/build-rubberband-checkpoint.sh")
endif()
add_library(plumdeck-rubberband-state INTERFACE)
target_include_directories(plumdeck-rubberband-state INTERFACE "${JUNCTION_RB_ROOT}/source")
target_link_libraries(plumdeck-rubberband-state INTERFACE "${JUNCTION_RB_LIBRARY}" "${JUNCTION_samplerate_LIBRARY}")
if(TARGET rubberband::rubberband)
 set_target_properties(rubberband::rubberband PROPERTIES IMPORTED_LOCATION "${JUNCTION_RB_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${JUNCTION_RB_ROOT}/source")
endif()

if(APPLE)
  target_link_libraries(plumdeck-rubberband-state INTERFACE "-framework Accelerate")
endif()
