set(JUNCTION_ST_ROOT "${CMAKE_CURRENT_LIST_DIR}/../build-deps/soundtouch")
if(WIN32)
  set(JUNCTION_ST_LIBRARY "${JUNCTION_ST_ROOT}/build/SoundTouch.lib")
else()
  set(JUNCTION_ST_LIBRARY "${JUNCTION_ST_ROOT}/build/libSoundTouch.a")
endif()
if(NOT EXISTS "${JUNCTION_ST_LIBRARY}")
  message(FATAL_ERROR "Build the pinned SoundTouch checkpoint dependency with scripts/build-soundtouch-checkpoint.sh")
endif()
add_library(plumdeck-soundtouch-state STATIC "${CMAKE_CURRENT_LIST_DIR}/../src/junction/soundtouch_state.cpp")
set_target_properties(plumdeck-soundtouch-state PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON)
target_include_directories(plumdeck-soundtouch-state PUBLIC "${JUNCTION_ST_ROOT}/include" "${CMAKE_CURRENT_LIST_DIR}/../src"
 PRIVATE "${JUNCTION_ST_ROOT}/source/include" "${JUNCTION_ST_ROOT}/source/source/SoundTouch")
target_link_libraries(plumdeck-soundtouch-state PUBLIC Qt6::Core "${JUNCTION_ST_LIBRARY}")
if(TARGET SoundTouch::SoundTouch)
  set_target_properties(SoundTouch::SoundTouch PROPERTIES IMPORTED_LOCATION "${JUNCTION_ST_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${JUNCTION_ST_ROOT}/include")
endif()
