"""Initial migration

Revision ID: 0fe588fb854e
Revises: 
Create Date: 2025-12-26 00:44:41.120546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fe588fb854e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    初期化は infra/database/schema.py の init_raw_db で行うため、
    ここでは何もしません。
    DuckDBの制約上、マイグレーションの自動生成が難しいため。
    """
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_embeddings')
    op.drop_table('track_analyses')
    op.drop_table('setlist_tracks')
    op.drop_table('presets')
    op.drop_table('lyrics')
    op.drop_index(op.f('ix_tracks_year'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_filepath'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_created_at'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_album'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('settings')
    op.drop_table('setlists')
    op.drop_table('prompts')
    # ### end Alembic commands ###
